const db = require('../config/sqlite');

class SystemSetting {
    static async get(key) {
        return new Promise((resolve, reject) => {
            const sql = 'SELECT value FROM system_settings WHERE key = ?';
            db.get(sql, [key], (err, row) => {
                if (err) return reject(err);
                if (!row) return resolve(null);
                try {
                    resolve(JSON.parse(row.value));
                } catch (e) {
                    resolve(row.value);
                }
            });
        });
    }

    static async getAll() {
        return new Promise((resolve, reject) => {
            const sql = 'SELECT * FROM system_settings ORDER BY key ASC';
            db.all(sql, [], (err, rows) => {
                if (err) return reject(err);
                const parsed = rows.map(row => {
                    let val;
                    try {
                        val = JSON.parse(row.value);
                    } catch (e) {
                        val = row.value;
                    }
                    return { ...row, value: val };
                });
                resolve(parsed);
            });
        });
    }

    static async update(key, value) {
        return new Promise((resolve, reject) => {
            const jsonValue = JSON.stringify(value);
            const sql = 'UPDATE system_settings SET value = ?, updated_at = CURRENT_TIMESTAMP WHERE key = ?';
            db.run(sql, [jsonValue, key], function (err) {
                if (err) return reject(err);
                if (this.changes === 0) {
                    const insSql = 'INSERT INTO system_settings (key, value, description, updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP)';
                    db.run(insSql, [key, jsonValue, 'Autogenerated setting'], function (iErr) {
                        if (iErr) return reject(iErr);
                        resolve(this.changes);
                    });
                } else {
                    resolve(this.changes);
                }
            });
        });
    }
}

module.exports = SystemSetting;
